/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LenderAdmin.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.form.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Number',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Column',
        'Ext.selection.CheckboxModel'
    ],

    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    region: 'center',
                    itemId: 'lendersfrm',
                    bodyPadding: 10,
                    title: 'Lenders',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'clearFieldsbtn',
                                    text: 'Clear fields to Add New Lender'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'updatebtn',
                                    text: 'Update this record'
                                },
                                {
                                    xtype: 'combobox',
                                    itemId: 'stateFiltercbo',
                                    width: 129,
                                    fieldLabel: 'State Filter',
                                    labelWidth: 70,
                                    name: 'filterState',
                                    value: 'KS',
                                    store: [
                                        'KS',
                                        'MO',
                                        'TX'
                                    ]
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'changeStatebtn',
                                    text: 'Change State'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'deletebtn',
                                    text: 'Delete this record'
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'container',
                            height: 36,
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    itemId: 'lenderIdcbo',
                                    margin: '0 5 0 5',
                                    width: 312,
                                    fieldLabel: 'lenderId',
                                    labelWidth: 55,
                                    name: 'lenderId',
                                    displayField: 'lenderId',
                                    queryMode: 'local',
                                    store: 'Lenders',
                                    typeAheadDelay: 100
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 5 0 5',
                                    width: 299,
                                    fieldLabel: 'lenderName',
                                    labelWidth: 75,
                                    name: 'name'
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '0 5 0 5',
                                    width: 134,
                                    fieldLabel: 'lenderState',
                                    labelWidth: 75,
                                    name: 'lenderState',
                                    store: [
                                        'KS',
                                        'MO',
                                        'TX'
                                    ]
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '0 5 0 5',
                                    width: 191,
                                    fieldLabel: 'financeType',
                                    labelWidth: 75,
                                    name: 'financeType',
                                    store: [
                                        'finance',
                                        'lease'
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 36,
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    margin: '0 5 0 5',
                                    width: 312,
                                    fieldLabel: 'street',
                                    labelWidth: 55,
                                    name: 'street'
                                },
                                {
                                    xtype: 'textfield',
                                    itemId: 'street2txt',
                                    margin: '0 5 0 5',
                                    width: 245,
                                    fieldLabel: 'street2',
                                    labelWidth: 55,
                                    name: 'street2'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 5 0 5',
                                    width: 393,
                                    fieldLabel: 'fullStreet',
                                    labelWidth: 55,
                                    name: 'fullStreet',
                                    readOnly: true
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 36,
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    margin: '0 5 0 5',
                                    width: 312,
                                    fieldLabel: 'city',
                                    labelWidth: 55,
                                    name: 'city'
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '0 5 0 5',
                                    width: 134,
                                    fieldLabel: 'state',
                                    labelWidth: 55,
                                    name: 'state'
                                },
                                {
                                    xtype: 'textfield',
                                    itemId: 'zipcodetxt',
                                    margin: '0 5 0 5',
                                    width: 157,
                                    fieldLabel: 'zipcode',
                                    labelWidth: 55,
                                    name: 'zipcode'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 5 0 5',
                                    width: 211,
                                    fieldLabel: 'phone',
                                    labelWidth: 55,
                                    name: 'phone'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 36,
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    margin: '0 5 0 5',
                                    width: 311,
                                    fieldLabel: 'csz',
                                    labelWidth: 55,
                                    name: 'csz'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 5 0 5',
                                    width: 311,
                                    fieldLabel: 'mongoId',
                                    labelWidth: 55,
                                    name: 'mongoId'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 36,
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'numberfield',
                                    margin: '0 5 0 5',
                                    width: 311,
                                    fieldLabel: 'reservePercentage',
                                    name: 'reservePercentage',
                                    maxValue: 1,
                                    minValue: 0
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 5 0 5',
                                    width: 311,
                                    fieldLabel: 'lendersDealerId',
                                    name: 'lendersDealerId'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 5 0 5',
                                    width: 311,
                                    fieldLabel: 'mongoIdLD',
                                    name: 'mongoIdLD'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 36,
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    margin: '0 5 0 5',
                                    fieldLabel: 'dealerIds',
                                    labelWidth: 55,
                                    name: 'dealerIds',
                                    displayField: 'dealerId',
                                    queryMode: 'local',
                                    store: 'DealerIds'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'addDealerIdToDealerIdsGrid',
                                    text: 'Add dealerId to this lender'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 600,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    itemId: 'dealersgrd',
                                    width: 181,
                                    title: 'Dealers assigned to this lender in this lenderState',
                                    store: 'DealerIdsGrid',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            width: 138,
                                            dataIndex: 'dealerId',
                                            text: 'DealerId'
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    itemId: 'removeDealerFromGridbtn',
                                                    text: 'Remove checked Dealers'
                                                }
                                            ]
                                        }
                                    ],
                                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                                    })
                                },
                                {
                                    xtype: 'form',
                                    flex: 1,
                                    bodyPadding: 10,
                                    title: 'Required Core Forms for this lender',
                                    items: [
                                        {
                                            xtype: 'container',
                                            height: 46,
                                            margin: '0 5 0 5',
                                            layout: {
                                                type: 'hbox',
                                                align: 'middle'
                                            },
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    margin: '0 5 0 5',
                                                    fieldLabel: 'formType',
                                                    labelWidth: 60,
                                                    name: 'formType',
                                                    displayField: 'name',
                                                    queryMode: 'local',
                                                    store: 'FormTypes'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    margin: '0 5 0 5',
                                                    width: 253,
                                                    fieldLabel: 'publicName',
                                                    labelWidth: 75,
                                                    name: 'publicName'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    margin: '0 5 0 5',
                                                    width: 217,
                                                    fieldLabel: 'formId',
                                                    labelWidth: 40,
                                                    name: 'formId'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    margin: '0 5 0 5',
                                                    width: 244,
                                                    fieldLabel: 'template Guid',
                                                    labelWidth: 60,
                                                    name: 'templateGuid'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    margin: '0 5 0 5',
                                                    width: 244,
                                                    fieldLabel: 'mongoId',
                                                    labelWidth: 60,
                                                    name: 'templateGuid'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'gridpanel',
                                            height: 389,
                                            itemId: 'formRequirementsgrd',
                                            title: 'Required Form Types and FormIds',
                                            store: 'FormRequirements',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    width: 115,
                                                    dataIndex: 'formType',
                                                    text: 'FormType'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    width: 174,
                                                    dataIndex: 'publicName',
                                                    text: 'PublicName'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    width: 177,
                                                    dataIndex: 'formId',
                                                    text: 'FormId'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    width: 182,
                                                    dataIndex: 'templateGuid',
                                                    text: 'TemplateGuid'
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    width: 201,
                                                    dataIndex: '_id',
                                                    text: '_id'
                                                }
                                            ]
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    text: 'Clear Fields to Add New Form'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Update this record'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Delete this form from Requirements'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'memoLenderid',
                                                    fieldLabel: 'LenderId',
                                                    labelWidth: 50
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'memoState',
                                                    width: 80,
                                                    fieldLabel: 'State',
                                                    labelWidth: 30
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});