/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LenderAdmin.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Number',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Column',
        'Ext.toolbar.Toolbar'
    ],

    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    region: 'center',
                    itemId: 'lendersfrm',
                    bodyPadding: 10,
                    title: 'Lenders',
                    items: [
                        {
                            xtype: 'container',
                            height: 36,
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    itemId: 'lenderIdcbo',
                                    margin: '0 5 0 5',
                                    width: 312,
                                    fieldLabel: 'lenderId',
                                    labelWidth: 55,
                                    name: 'lenderId',
                                    displayField: 'lenderId',
                                    queryMode: 'local',
                                    store: 'Lenders',
                                    typeAheadDelay: 100
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 5 0 5',
                                    width: 299,
                                    fieldLabel: 'lenderName',
                                    labelWidth: 75,
                                    name: 'name'
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '0 5 0 5',
                                    width: 134,
                                    fieldLabel: 'lenderState',
                                    labelWidth: 75,
                                    name: 'lenderState',
                                    store: [
                                        'KS',
                                        'MO',
                                        'TX'
                                    ]
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '0 5 0 5',
                                    width: 191,
                                    fieldLabel: 'financeType',
                                    labelWidth: 75,
                                    name: 'financeType',
                                    store: [
                                        'finance',
                                        'lease'
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 36,
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    margin: '0 5 0 5',
                                    width: 312,
                                    fieldLabel: 'street',
                                    labelWidth: 55,
                                    name: 'street'
                                },
                                {
                                    xtype: 'textfield',
                                    itemId: 'street2txt',
                                    margin: '0 5 0 5',
                                    width: 245,
                                    fieldLabel: 'street2',
                                    labelWidth: 55,
                                    name: 'street2'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 5 0 5',
                                    width: 393,
                                    fieldLabel: 'fullStreet',
                                    labelWidth: 55,
                                    name: 'fullStreet',
                                    readOnly: true
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 36,
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    margin: '0 5 0 5',
                                    width: 312,
                                    fieldLabel: 'city',
                                    labelWidth: 55,
                                    name: 'city'
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '0 5 0 5',
                                    width: 134,
                                    fieldLabel: 'state',
                                    labelWidth: 55,
                                    name: 'state'
                                },
                                {
                                    xtype: 'textfield',
                                    itemId: 'zipcodetxt',
                                    margin: '0 5 0 5',
                                    width: 157,
                                    fieldLabel: 'zipcode',
                                    labelWidth: 55,
                                    name: 'zipcode'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 5 0 5',
                                    width: 211,
                                    fieldLabel: 'phone',
                                    labelWidth: 55,
                                    name: 'phone'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 36,
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    margin: '0 5 0 5',
                                    width: 311,
                                    fieldLabel: 'csz',
                                    labelWidth: 55,
                                    name: 'csz'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 5 0 5',
                                    width: 311,
                                    fieldLabel: 'mongoId',
                                    labelWidth: 55,
                                    name: 'mongoId'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 36,
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'numberfield',
                                    margin: '0 5 0 5',
                                    width: 311,
                                    fieldLabel: 'reservePercentage',
                                    name: 'reservePercentage',
                                    maxValue: 1,
                                    minValue: 0
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 5 0 5',
                                    width: 311,
                                    fieldLabel: 'lendersDealerId',
                                    name: 'lendersDealerId'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 5 0 5',
                                    width: 311,
                                    fieldLabel: 'mongoIdLD',
                                    name: 'mongoIdLD'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 36,
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    margin: '0 5 0 5',
                                    fieldLabel: 'dealerIds',
                                    labelWidth: 55,
                                    name: 'dealerIds',
                                    displayField: 'dealerId',
                                    multiSelect: true,
                                    queryMode: 'local',
                                    store: 'DealerIds'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'addDealerIdToDealerIdsGrid',
                                    text: 'Add dealerId to this lender'
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            width: 1019,
                            title: 'Dealers assigned to this lender in this lenderState',
                            store: 'DealerIdsGrid',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    width: 201,
                                    dataIndex: 'dealerId',
                                    text: 'DealerId'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            text: 'Remove this dealer from this lender in this lenderState'
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'clearFieldsbtn',
                                    text: 'Clear fields to Add New Lender'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'updatebtn',
                                    text: 'Update this record'
                                },
                                {
                                    xtype: 'combobox',
                                    itemId: 'stateFiltercbo',
                                    width: 129,
                                    fieldLabel: 'State Filter',
                                    labelWidth: 70,
                                    name: 'filterState',
                                    value: 'KS',
                                    store: [
                                        'KS',
                                        'MO',
                                        'TX'
                                    ]
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'changeStatebtn',
                                    text: 'Change State'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'deletebtn',
                                    text: 'Delete this record'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});