/*
 * File: app/model/Form.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LenderAdmin.model.Form', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'formCategory'
        },
        {
            name: 'formType'
        },
        {
            name: 'formId'
        },
        {
            name: 'publicName'
        },
        {
            name: 'templateGuid'
        },
        {
            name: '_id'
        },
        {
            name: 'ownershipType'
        },
        {
            name: 'states'
        },
        {
            name: 'lenders'
        },
        {
            name: 'dealers'
        },
        {
            name: 'manufacturers'
        },
        {
            name: 'dealTypes'
        },
        {
            name: 'fixedFees'
        },
        {
            name: 'fixedProducts'
        },
        {
            name: 'feeLinesAvailable'
        },
        {
            name: 'fixedProductLinesAvailable'
        },
        {
            name: 'line5LinesAvailable'
        }
    ]
});