/*
 * File: app/model/Lender.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LenderAdmin.model.Lender', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'lenderId'
        },
        {
            name: 'name'
        },
        {
            name: 'lenderState'
        },
        {
            name: 'street'
        },
        {
            name: 'street2'
        },
        {
            name: 'fullStreet'
        },
        {
            name: 'city'
        },
        {
            name: 'state'
        },
        {
            name: 'zipcode'
        },
        {
            name: 'phone'
        },
        {
            name: 'csz'
        },
        {
            name: 'dealerIds'
        },
        {
            name: '_id'
        },
        {
            name: 'financeType'
        },
        {
            name: 'fin'
        }
    ]
});