/*
 * File: app/controller/MongoCalls.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LenderAdmin.controller.MongoCalls', {
    extend: 'Ext.app.Controller',

    onLenderIdcboSelect: function(combo, records, eOpts) {

        var form = Ext.ComponentQuery.query('#lendersfrm')[0];
        form.getForm().setValues(records[0].data);
        // you have to set the _id field to mongoId
        Ext.ComponentQuery.query('field[name=mongoId]')[0].setValue(records[0].data._id);

        // set the store values for dealerId
        // load the dealerIds into the grid
        var dealers = records[0].data.dealerIds;
        var dealerId  = {};
        var dealerIds = [];
        Ext.Array.forEach(dealers, function(item,index,self){
            dealerId = {
                dealerId:item
            };
            dealerIds.push(dealerId);
        });
        store = Ext.getStore('DealerIdsGrid');
        store.loadData(dealerIds);

        // make a mongo call to get the matching reservePercentage and lendersDealerId if it exists
        this.getReservePercentageAndLendersDealerId();
    },

    onUpdatebtnClick: function(button, e, eOpts) {
        // calc updateDoc
        var updateDoc = Ext.ComponentQuery.query('#lendersfrm')[0].getForm().getValues();
        delete updateDoc.mongoIdLD;
        delete updateDoc.reservePercentage;
        delete updateDoc.lendersDealerId;
        delete updateDoc.filterState;
        delete updateDoc.dealerIds;
        delete updateDoc.mongoId;

        var dealerIds = [];
        var store = Ext.getStore('DealerIdsGrid');
        var values = store.data.items;
        Ext.Array.forEach(values, function(item,index,self){
            dealerIds.push(item.data.dealerId);
        });
        updateDoc.dealerIds = dealerIds;
        // calc queryDoc
        var lenderId    = Ext.ComponentQuery.query('field[name=lenderId]')[0].getValue();
        var dealerId    = Ext.ComponentQuery.query('field[name=dealerIds]')[0].getValue();
        var financeType = Ext.ComponentQuery.query('field[name=financeType]')[0].getValue();
        var lenderState = Ext.ComponentQuery.query('field[name=lenderState]')[0].getValue();
        if(!lenderId || !dealerId || !financeType || !lenderState){
            alert('you have to fill out lenderId, dealerId, lenderState and financeType otherwise you cannot save a record');
            return;
        }
        var queryDoc = {
            lenderId   :lenderId,
            financeType:financeType,
            lenderState:lenderState
        };

        // set collectionName
        var collectionName = "lenders";

        // set mongoCall
        var mongoCall = "upsertDoc";

        this.upsertLenderRecord(collectionName,queryDoc,updateDoc,mongoCall);

    },

    onLendersfrmAfterRender: function(component, eOpts) {
        this.getAllLenders();
        //this.getAllForms();
    },

    onStateFiltercboChange: function(field, newValue, oldValue, eOpts) {
        this.getAllLenders();
    },

    onLenderIdcboExpand: function(field, eOpts) {

        this.getAllLenders();
    },

    onDeletebtnClick: function(button, e, eOpts) {
        var mongoId = Ext.ComponentQuery.query('field[name=mongoId]')[0].getValue();
        if(!mongoId){
            alert("you can't delete a record that doesn't exist in mongo");
        }
        else {
            this.deleteRecord(mongoId,"lenders","deleteDoc");
        }
    },

    onRefreshFormsListbtnClick: function(button, e, eOpts) {
        Ext.ComponentQuery.query('#formTypeFiltercbo')[0].setValue("");
        this.getAllForms();
    },

    getAllLenders: function() {
        var collectionName = "lenders";
        var mongoCall      = "getDocs";
        var lenderState    = Ext.ComponentQuery.query('#stateFiltercbo')[0].getValue();
        var query          = {"lenderState":lenderState};
        var store          = Ext.getStore('Lenders');
        store.removeAll();

        Ext.Ajax.request({
            url: nodeJsService + "collection/" + mongoCall,
            success: function(response,err){
                var docsArray = JSON.parse(response.responseText);
                store = Ext.getStore("Lenders");
                Ext.Array.forEach(docsArray,function(item,index,self){
                    store.add(item);
                });
            },
            failure: function(response,err){
                alert("wasn't able to get docs from collection " + collectionName);
            },
            method: 'GET',
            params: {
                "query"      :JSON.stringify(query),
                "collectionS":collectionName
            }
        });

    },

    getAllForms: function() {
        var collectionName = "forms";
        var query          = {};
        query              = JSON.stringify(query);
        debugger;
        var store          = Ext.getStore('Forms');
        store.removeAll();
        this.getAllDocs(collectionName,query,store);

    },

    getAllDocs: function(collectionName, query, store) {
        scope = this;
        Ext.Ajax.request({
            url: nodeJsService + "collection/getDocs",
            success: function(response,err){
                var docsArray = JSON.parse(response.responseText);
                debugger;
                store.clearFilter();
                store.loadData(docsArray);
            },
            failure: function(response,err){
                alert("wasn't able to get docs from collection " + collectionName);
            },
            method: 'GET',
            params: {
                "query"      :query,
                "collectionS":collectionName
            }
        });

    },

    getReservePercentageAndLendersDealerId: function() {
        var collectionName = "lenderDealer";
        var mongoCall      = "getDocs";
        // create query
        var dealerId       = Ext.ComponentQuery.query('field[name=dealerIds]')[0].getValue();
        dealerId = dealerId[0];
        var lenderId       = Ext.ComponentQuery.query('field[name=lenderId]')[0].getValue();
        var financeType    = Ext.ComponentQuery.query('field[name=financeType]')[0].getValue();
        var query          = {"dealerId":dealerId,"lenderId":lenderId,"financeType":financeType};

        Ext.Ajax.request({
            url: nodeJsService + "collection/" + mongoCall,
            success: function(response,err){
                var docsArray = JSON.parse(response.responseText);

                var doc = docsArray[0];
                if(Ext.isDefined(doc)){
                    Ext.ComponentQuery.query('field[name=reservePercentage]')[0].setValue(doc.reservePercentage);
                    Ext.ComponentQuery.query('field[name=lendersDealerId]')[0].setValue(doc.lendersDealerId);
                    Ext.ComponentQuery.query('field[name=mongoIdLD]')[0].setValue(doc._id);

                }
                else {

                    Ext.ComponentQuery.query('field[name=reservePercentage]')[0].setValue("");
                    Ext.ComponentQuery.query('field[name=lendersDealerId]')[0].setValue("");
                    Ext.ComponentQuery.query('field[name=mongoIdLD]')[0].setValue("");
                    alert('there is no lenderDealer record matching this lender');
                }
            },
            failure: function(response,err){
                alert("wasn't able to get docs from collection " + collectionName);
            },
            method: 'GET',
            params: {
                "query"      :JSON.stringify(query),
                "collectionS":collectionName
            }
        });

    },

    upsertLenderRecord: function(collectionName, queryDoc, updateDoc, mongoCall) {
        var scope = this;
        Ext.Ajax.request({
            url: nodeJsService + "collection/"+mongoCall,
            success: function(response,err){
                debugger;
                if (response.responseText=="true"){
                    alert("upserted the document");
                }
                //upsert the lenderDealerRecord
                scope.upsertLenderDealerRecord();
            },
            failure: function(response,err){
                alert("No upsert");
            },
            method: 'POST',
            params: {
                "collectionS":collectionName,
                "updateDoc"  :JSON.stringify(updateDoc),
                "queryDoc"   :JSON.stringify(queryDoc)
            }
        });
    },

    upsertLenderDealerRecord: function() {
        var collectionName = "lenderDealer";
        var mongoCall      = "upsertDoc";
        var dealerId       = Ext.ComponentQuery.query('field[name=dealerIds]')[0].getValue();
        dealerId           = dealerId[0];
        var lenderId       = Ext.ComponentQuery.query('field[name=lenderId]')[0].getValue();
        var financeType    = Ext.ComponentQuery.query('field[name=financeType]')[0].getValue();
        var query          = {"dealerId":dealerId,"lenderId":lenderId,"financeType":financeType};

        var updateDoc = {
            lenderId:lenderId,
            financeType:financeType,
            dealerId:dealerId,
            reservePercentage:Ext.ComponentQuery.query("field[name=reservePercentage]")[0].getValue(),
            lendersDealerId  :Ext.ComponentQuery.query("field[name=lendersDealerId]")[0].getValue()
        };

        Ext.Ajax.request({
            url: nodeJsService + "collection/" + mongoCall,
            success: function(response,err){
                alert("upserted the lenderDealerRecord");
            },
            failure: function(response,err){
                alert("wasn't able to upsert the lenderDealer record");
            },
            method: 'POST',
            params: {
                "queryDoc"   :JSON.stringify(query),
                "collectionS":collectionName,
                "updateDoc"  :JSON.stringify(updateDoc)
            }
        });

    },

    deleteRecord: function(mongoId, collectionName, mongoCall) {
        var scope = this;
        Ext.Ajax.request({
            url: nodeJsService + "collection/" + mongoCall,
            success: function(response,err){
                var value = JSON.parse(response.responseText);
                debugger;
                var mongoIdLD = Ext.ComponentQuery.query('field[name=mongoIdLD]')[0].getValue();
                if(mongoIdLD){
                    scope.deleteRecord(mongoIdLD,"lenderDealer","deleteDoc");
                }
                debugger;
            },
            failure: function(response,err){
                alert("wasn't able to delete doc from collection: " + collectionName);
            },
            method: 'GET',
            params: {
                "mongoId"    :mongoId,
                "collectionS":collectionName
            }
        });
    },

    getLenderFormRequirements: function() {
        var collectionName = "formRequirements";
        var mongoCall      = "getDocs";
        var lenderState    = Ext.ComponentQuery.query('field[name=lenderState]')[0].getValue();
        var lenderId       = Ext.ComponentQuery.query('field[name=lenderId]')[0].getValue();
        var query          = {"lenderState":lenderState, lenderId:lenderId};
        var store          = Ext.getStore('FormRequirements');
        store.removeAll();

        Ext.Ajax.request({
            url: nodeJsService + "collection/" + mongoCall,
            success: function(response,err){
                var docsArray = JSON.parse(response.responseText);
                store = Ext.getStore("FormRequirements");
                store.loadData(docsArray);
            },
            failure: function(response,err){
                alert("wasn't able to get docs from collection " + collectionName);
            },
            method: 'GET',
            params: {
                "query"      :JSON.stringify(query),
                "collectionS":collectionName
            }
        });

    },

    init: function(application) {
        this.control({
            "#lenderIdcbo": {
                select: this.onLenderIdcboSelect,
                expand: this.onLenderIdcboExpand
            },
            "#updatebtn": {
                click: this.onUpdatebtnClick
            },
            "#lendersfrm": {
                afterrender: this.onLendersfrmAfterRender
            },
            "#stateFiltercbo": {
                change: this.onStateFiltercboChange
            },
            "#deletebtn": {
                click: this.onDeletebtnClick
            },
            "#refreshFormsListbtn": {
                click: this.onRefreshFormsListbtnClick
            }
        });
    }

});
